#!/usr/bin/env bash


# ---------------------------------------------------------
# Prerequisites
# ---------------------------------------------------------

# Consistent package location
HOMEBREW_OPT_DIR=$(brew --prefix $(basename $0))

# Where the profiles are stored
PROFILES_DIR="${HOMEBREW_OPT_DIR}/profiles"

# Default profiles
GRAY_LINEAR_PROFILE_DEFAULT="Gray-elle-V4-g10.icc"
SRGB_V4_PROFILE_DEFAULT="sRGB_ICC_v4_Appearance.icc"

# ---------------------------------------------------------
# No parameters given; show summary
# ---------------------------------------------------------

if [ "$#" -eq 0 ]; then

	echo "1. Usage:"
	echo "$(basename $0) [command]"
	echo;
	echo "2. Available commands:"
	echo "directory     Display the directory where the ICC profiles are stored"
	echo "gray-linear   Full path to profile '${GRAY_LINEAR_PROFILE_DEFAULT}'"
	echo "srgb-v4       Full path to profile '${SRGB_V4_PROFILE_DEFAULT}'"
	echo "summary       Display a summary of profiles coming with this package."
	echo;
	exit;
fi


# ---------------------------------------------------------
# Handle parameters
# ---------------------------------------------------------


while test $# -gt 0
do
    case "$1" in
        directory)
		echo $PROFILES_DIR
            	;;

        gray-linear)
	   	ls -1 "${PROFILES_DIR}/${GRAY_LINEAR_PROFILE_DEFAULT}"
        	;;

        srgb-v4)
		ls -1 "${PROFILES_DIR}/${SRGB_V4_PROFILE_DEFAULT}"
            	;;

        summary)
		echo;
		echo "These ICC profiles came with Homebrew formula tomkyle/negatives/iccprofiles."
		echo "<https://github.com/tomkyle/negatives-iccprofiles>"
		echo;

		echo "--------------------------------------------------------------------------";
		echo "1. Gray profiles from Elle Stone's Well-Behaved ICC Profiles"
		echo "<http://ninedegreesbelow.com/photography/lcms-make-icc-profiles.html#Gray>"
		echo;
		ls -1 "${PROFILES_DIR}"/Gray*
		echo;

		echo "--------------------------------------------------------------------------";
		echo "2. sRGB v4 Appearance profile from ICC/International Color Consortium"
		echo "<http://www.color.org/profiles/srgb_appearance.xalter>"
		echo;
		ls -1 "${PROFILES_DIR}"/sRGB*
		echo;

		echo "--------------------------------------------------------------------------";
		echo;
            	;;
    esac
    shift
done

exit 0

