#!/usr/bin/env bash


# ---------------------------------------------------------
# Prerequisites
# ---------------------------------------------------------

# Directory where this script lives in
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Consistent package location
HOMEBREW_OPT_DIR=$(brew --prefix $(basename $0))

# Where the profiles are stored
PROFILES_DIR="${HOMEBREW_OPT_DIR}/profiles"

# Default profiles
GRAY_LINEAR_PROFILE_DEFAULT="Gray-elle-V4-g10.icc"
SRGB_V4_PROFILE_DEFAULT="sRGB_ICC_v4_Appearance.icc"

# ---------------------------------------------------------
# No parameters given; show summary
# ---------------------------------------------------------

if [ "$#" -eq 0 ]; then
	if [ -f "${HOMEBREW_OPT_DIR}/USAGE.txt" ]; then
	   	cat "${HOMEBREW_OPT_DIR}/USAGE.txt"
	else
		cat "${SCRIPT_DIR}/USAGE.txt"
	fi

	echo;
	if [ -f "${HOMEBREW_OPT_DIR}/CREDITS.txt" ]; then
	   	cat "${HOMEBREW_OPT_DIR}/CREDITS.txt"
	else
		cat "${SCRIPT_DIR}/CREDITS.txt"
	fi
	echo;
	exit;
fi


# ---------------------------------------------------------
# Handle parameters
# ---------------------------------------------------------


while test $# -gt 0
do
    case "$1" in
        directory)
		echo $PROFILES_DIR
            	;;

        gray-linear)
	   	ls -1 "${PROFILES_DIR}/${GRAY_LINEAR_PROFILE_DEFAULT}"
        	;;

        srgb-v4)
		ls -1 "${PROFILES_DIR}/${SRGB_V4_PROFILE_DEFAULT}"
            	;;

        summary)
		echo;
		echo "These ICC profiles came with Homebrew formula tomkyle/negatives/iccprofiles."
		echo "<https://github.com/tomkyle/negatives-iccprofiles>"
		echo;

		echo "--------------------------------------------------------------------------";
		echo "1. Gray profiles from Elle Stone's Well-Behaved ICC Profiles"
		echo "<http://ninedegreesbelow.com/photography/lcms-make-icc-profiles.html#Gray>"
		echo;
		ls -1 "${PROFILES_DIR}"/Gray*
		echo;

		echo "--------------------------------------------------------------------------";
		echo "2. sRGB v4 Appearance profile from ICC/International Color Consortium"
		echo "<http://www.color.org/profiles/srgb_appearance.xalter>"
		echo;
		ls -1 "${PROFILES_DIR}"/sRGB*
		echo;

		echo "--------------------------------------------------------------------------";
		echo;
            	;;
    esac
    shift
done

exit 0

